version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    restart: on-failure
    env_file:
      - ../.env
    volumes:
      - mariadb:/var/lib/mysql:rw
    networks:
      - inception_network
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    expose:
      - "9000"
    restart: on-failure
    env_file:
      - ../.env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html:rw
    networks:
      - inception_network
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: on-failure
    ports:
      - "443:443"
    env_file:
      - ../.env
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html:rw
    networks:
      - inception_network
volumes:
  mariadb:
    driver: local 
    driver_opts:
      device: /home/michel-batista/data/mariadb
      type: none
      o: bind
  wordpress:
    driver: local 
    driver_opts:
      device: /home/michel-batista/data/wordpress
      type: none
      o: bind
networks:
  inception_network: