# version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    env_file:
      - ../.env
    volumes:
      - wordpress:/var/www/html/:rw
    networks:
      - inception_network
  wordpress:
    build:
      context: ./requirements/wordpress
      args:
      - SQL_DB
      - SQL_USR
      - SQL_PASS
      - SQL_HOST
      - WP_URL
      - WP_TITLE
      - WP_USER
      - WP_EMAIL
      - WP_PASS
      - WP_ADM_USR
      - WP_ADM_EML
      - WP_ADM_PASS
    container_name: wordpress
    restart: always
    env_file:
      - ../.env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html/:rw
    networks:
      - inception_network
  mariadb:
    build:
      context: ./requirements/mariadb
      args:
      - SQL_DB
      - SQL_USR
      - SQL_PASS
      - SQL_ROOT_PASS
    container_name: mariadb
    restart: always
    env_file:
      - ../.env
    volumes:
      - mariadb:/var/lib/mysql/:rw
    networks:
      - inception_network
volumes:
  wordpress:
    driver_opts:
      device: /${HOME}/data/wordpress
      type: none
      o: bind
  mariadb:
    driver_opts:
      device: /${HOME}/data/mariadb
      type: none
      o: bind
networks:
  inception_network:
